name: Deploy to Staging
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22 # Explicitly set (default is 22)
          script: |
            echo "Starting deployment to staging server..."
            cd DevOps-bms
            echo "Pulling latest changes..."
            git pull origin main
            echo "Checking pnpm existence. if not then installing..."
            which pnpm || npm install -g pnpm
            echo "Installing dependencies..."
            pnpm install
            echo "Building project..."
            pnpm run build
            echo "Restarting PM2 processes..."
            pm2 restart all
            echo "Deployment to staging server completed successfully."
